/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import panamahitek.Arduino.PanamaHitek_Arduino;
import java.sql.*;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SKYWALKER
 */
public class Formulario extends javax.swing.JFrame {

    PanamaHitek_Arduino arduino = new PanamaHitek_Arduino();
    
    public Formulario() {
        
        initComponents();
        mostrardatos("");
        mostrardatos2("");
         //Color JFrame
       

        //Color JPanel
   
        
        try {
            arduino.arduinoTX("COM3", 9600);
             
            
        } catch (Exception ex) {
            Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    void mostrardatos(String valor){
      DefaultTableModel modelo = new DefaultTableModel();
      modelo.addColumn("NOMBRE");
      modelo.addColumn("LICOR");
      modelo.addColumn("JUGO");
      tbproduc.setModel(modelo);
      String sql="";
      if(valor.equals(""))
      {
         sql="SELECT * FROM bebidas";
      }
      else{
        sql="SELECT * FROM bebidas WHERE nom ='"+valor+"'";
  } 
  
      String []datos = new String [3];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                modelo.addRow(datos);
            }
            tbproduc.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        void mostrardatos2(String valor){
      DefaultTableModel modelo = new DefaultTableModel();
      modelo.addColumn("NOMBRE");
      modelo.addColumn("FECHA");
      modelo.addColumn("HORA");
      er.setModel(modelo);
      String sql="";
      if(valor.equals(""))
      {
         sql="SELECT * FROM he";
      }
      else{
        sql="SELECT * FROM he WHERE nom ='"+valor+"'";
  } 
  
      String []datos = new String [3];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                modelo.addRow(datos);
            }
            er.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
        }
  }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */ 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        buscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbproduc = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        er = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 255));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setToolTipText("");
        jPanel1.setMaximumSize(getMaximumSize());
        jPanel1.setLayout(null);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 255));
        jButton2.setText("VODKA ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(420, 70, 280, 170);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("CUBA LIBRE  ");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(720, 250, 290, 170);

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("ENIBRIATOR");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(470, -10, 520, 100);
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 204));
        jButton4.setText("WHISKEY");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(420, 440, 280, 170);

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 204));
        jButton5.setText("PALOMA");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(420, 250, 290, 170);
        jPanel1.add(buscar);
        buscar.setBounds(10, 60, 150, 30);

        tbproduc.setBackground(new java.awt.Color(255, 153, 0));
        tbproduc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbproduc);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 160, 400, 140);

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(170, 40, 150, 70);

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(330, 30, 70, 100);

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 255));
        jButton6.setText("CABALLITO");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(710, 70, 280, 170);

        er.setBackground(new java.awt.Color(255, 153, 0));
        er.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(er);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 350, 400, 160);

        jLabel2.setFont(new java.awt.Font("Ravie", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DANIEL ISLAS CUERO");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(660, 660, 230, 40);

        jLabel3.setBackground(new java.awt.Color(153, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("UNIVERSIDAD PRIVADA DEL ESTADO DE MEXICO");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(650, 690, 370, 20);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("BEBIDAS HECHAS");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 310, 240, 34);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(-30, -10, 1480, 740);

        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(530, 540, 160, 90);

        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(600, 530, 34, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        
        try {
            
             Calendar calendario = Calendar.getInstance();
        String e = "CUBA LIBRE";
        int hora, min, seg, d, m, a;
            d = calendario.get(Calendar.DATE);
        m = calendario.get(Calendar.MONTH);
        a = calendario.get(Calendar.YEAR);
        hora = calendario.get(Calendar.HOUR_OF_DAY);
        min = calendario.get(Calendar.MINUTE);
        seg = calendario.get(Calendar.SECOND);
        PreparedStatement pst = cn.prepareStatement("INSERT INTO he (nom, FECHA, HORA) VALUES (?,?,?)");
        
String c = "";
c = String.valueOf(d);
c= Integer.toString(d);
String x = "";
x = String.valueOf(m);
x= Integer.toString(m);  
String o = "";
o = String.valueOf(a);
o= Integer.toString(a);
String i = "";
i = String.valueOf(hora);
i= Integer.toString(hora);
String q = "";
q = String.valueOf(min);
q= Integer.toString(min);
String z = "";
z = String.valueOf(seg);
z= Integer.toString(seg);
            pst.setString(1, e);
            pst.setString(2, c + "/" + x + "/" + o);
            pst.setString(3, i + ":" + q + ":" + z);
            pst.executeUpdate();
            mostrardatos2("");
            arduino.sendData("6");
        } catch (Exception ex) {
            Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
 
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            
           Calendar calendario = Calendar.getInstance();
        String e = "VODKA";
        int hora, min, seg, d, m, a;
            d = calendario.get(Calendar.DATE);
        m = calendario.get(Calendar.MONTH);
        a = calendario.get(Calendar.YEAR);
        hora = calendario.get(Calendar.HOUR_OF_DAY);
        min = calendario.get(Calendar.MINUTE);
        seg = calendario.get(Calendar.SECOND);
        PreparedStatement pst = cn.prepareStatement("INSERT INTO he (nom, FECHA, HORA) VALUES (?,?,?)");
        
String c = "";
c = String.valueOf(d);
c= Integer.toString(d);
String x = "";
x = String.valueOf(m);
x= Integer.toString(m);  
String o = "";
o = String.valueOf(a);
o= Integer.toString(a);
String i = "";
i = String.valueOf(hora);
i= Integer.toString(hora);
String q = "";
q = String.valueOf(min);
q= Integer.toString(min);
String z = "";
z = String.valueOf(seg);
z = Integer.toString(seg);
            pst.setString(1, e);
            pst.setString(2, c + "/" + x + "/" + o);
            pst.setString(3, i + ":" + q + ":" + z);
            pst.executeUpdate();
            mostrardatos2("");
            arduino.sendData("4");
        } catch (Exception ex) {
            Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
        }
                
             
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            
            Calendar calendario = Calendar.getInstance();
        String e = "WHISKEY";
        int hora, min, seg, d, m, a;
            d = calendario.get(Calendar.DATE);
        m = calendario.get(Calendar.MONTH);
        a = calendario.get(Calendar.YEAR);
        hora = calendario.get(Calendar.HOUR_OF_DAY);
        min = calendario.get(Calendar.MINUTE);
        seg = calendario.get(Calendar.SECOND);
        PreparedStatement pst = cn.prepareStatement("INSERT INTO he (nom, FECHA, HORA) VALUES (?,?,?)");
        
String c = "";
c = String.valueOf(d);
c= Integer.toString(d);
String x = "";
x = String.valueOf(m);
x= Integer.toString(m);  
String o = "";
o = String.valueOf(a);
o= Integer.toString(a);
String i = "";
i = String.valueOf(hora);
i= Integer.toString(hora);
String q = "";
q = String.valueOf(min);
q= Integer.toString(min);
String z = "";
z = String.valueOf(seg);
z= Integer.toString(seg);
            pst.setString(1, e);
            pst.setString(2, c + "/" + x + "/" + o);
            pst.setString(3, i + ":" + q + ":" + z);
            pst.executeUpdate();
            mostrardatos2("");
            arduino.sendData("3");
        } catch (Exception ex) {
            Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        mostrardatos(buscar.getText());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        mostrardatos("");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            // TODO add your handling code here:
            
            Calendar calendario = Calendar.getInstance();
        String e = "PALOMA";
        int hora, min, seg, d, m, a;
            d = calendario.get(Calendar.DATE);
        m = calendario.get(Calendar.MONTH);
        a = calendario.get(Calendar.YEAR);
        hora = calendario.get(Calendar.HOUR_OF_DAY);
        min = calendario.get(Calendar.MINUTE);
        seg = calendario.get(Calendar.SECOND);
        PreparedStatement pst = cn.prepareStatement("INSERT INTO he (nom, FECHA, HORA) VALUES (?,?,?)");
        
String c = "";
c = String.valueOf(d);
c= Integer.toString(d);
String x = "";
x = String.valueOf(m);
x= Integer.toString(m);  
String o = "";
o = String.valueOf(a);
o= Integer.toString(a);
String i = "";
i = String.valueOf(hora);
i= Integer.toString(hora);
String q = "";
q = String.valueOf(min);
q= Integer.toString(min);
String z = "";
z = String.valueOf(seg);
z= Integer.toString(seg);
            pst.setString(1, e);
            pst.setString(2, c + "/" + x + "/" + o);
            pst.setString(3, i + ":" + q + ":" + z);
            pst.executeUpdate();
            mostrardatos2("");
             arduino.sendData("2");
        } catch (Exception ex) {
            Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed
 
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            // TODO add your handling code here:
           
            Calendar calendario = Calendar.getInstance();
        String e = "CABALLITO";
        int hora, min, seg, d, m, a;
            d = calendario.get(Calendar.DATE);
        m = calendario.get(Calendar.MONTH);
        a = calendario.get(Calendar.YEAR);
        hora = calendario.get(Calendar.HOUR_OF_DAY);
        min = calendario.get(Calendar.MINUTE);
        seg = calendario.get(Calendar.SECOND);
        PreparedStatement pst = cn.prepareStatement("INSERT INTO he (nom, FECHA, HORA) VALUES (?,?,?)");
        
String c = "";
c = String.valueOf(d);
c= Integer.toString(d);
String x = "";
x = String.valueOf(m);
x= Integer.toString(m);  
String o = "";
o = String.valueOf(a);
o= Integer.toString(a);
String i = "";
i = String.valueOf(hora);
i= Integer.toString(hora);
String q = "";
q = String.valueOf(min);
q= Integer.toString(min);
String z = "";
z = String.valueOf(seg);
z= Integer.toString(seg);
            pst.setString(1, e);
            pst.setString(2, c + "/" + x + "/" + o);
            pst.setString(3, i + ":" + q + ":" + z);
            pst.executeUpdate();
            mostrardatos2("");
             arduino.sendData("1");
        } catch (Exception ex) {
            Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */  
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscar;
    private javax.swing.JTable er;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbproduc;
    // End of variables declaration//GEN-END:variables
conectar cc = new conectar();
Connection cn = cc.conexion();
}
